name: anyscale-ragbot
applications:
  - import_path: rag.serve:deployment
image_uri: anyscale/image/anyscale-ragbot:1
compute_config: anyscale-ragbot:1
working_dir: "."
env_vars:
  ANYSCALE_ASSISTANT_SECRETS: "anyscale-assistant-prod"  # pragma: allowlist secret
  ANYSCALE_ASSISTANT_LOGS: "/mnt/shared_storage/emmy/logs/info.log"
  ANYSCALE_ASSISTANT_INDEX: "/mnt/shared_storage/emmy/production/index.sql"
  ANYSCALE_ASSISTANT_EMBEDDING_MODEL: "text-embedding-3-large"
  ANYSCALE_ASSISTANT_RERANKER_MODEL: "/mnt/shared_storage/ray-assistant-data/reranker.pkl"
